CREATE TABLE Pacientes(
	PacienteId int IDENTITY(1,1) PRIMARY KEY NOT NULL,
	isDeficiente bit NOT NULL,
	ContatoEmergencia  nvarchar(20) NOT NULL,
	Nome nvarchar(200) NOT NULL,
	Email nvarchar(200) NOT NULL,
	CPF nvarchar(11) NOT NULL,
	Senha nvarchar(257) NOT NULL,
	DataNascimento [datetime2](7) NOT NULL,
	Estado nvarchar(50) NOT NULL,
	FotoPerfil nvarchar(500) NOT NULL,
	Logradouro nvarchar(500) NOT NULL,
	Numero int NOT NULL,
	Profissao nvarchar(200) NOT NULL,
	Telefone nvarchar(20) NOT NULL,
	TipoCliente int NOT NULL,
);

CREATE TABLE Especialistas(
	EspecialistaId int IDENTITY(1,1) NOT NULL,
	IdentificacaoProf nvarchar(max) NOT NULL,
	Especialidade nvarchar(max) NOT NULL,
	Nome nvarchar(200) NOT NULL,
	Email nvarchar(200) NOT NULL,
	CPF nvarchar(11) NOT NULL,
	Senha nvarchar(257) NOT NULL,
	DataNascimento [datetime2](7) NOT NULL,
	Estado nvarchar(50) NOT NULL,
	FotoPerfil nvarchar(500) NOT NULL,
	Logradouro nvarchar(500) NOT NULL,
	Numero int NOT NULL,
	Profissao nvarchar(200) NOT NULL,
	Telefone nvarchar(20) NOT NULL,
	TipoCliente int NOT NULL,
);